[tool.poetry]
name = "encryption1"
version = "0.1.0"
description = ""
authors = ["Arslan Giniiatullin <ars2003lan@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

